import { createClient } from '@/utils/supabase/server';
import React from 'react'
import { Card, Col, Container, Row } from 'react-bootstrap';
import ProductForm from '../ProductForm';
import Link from 'next/link';

export const metadata = {
  title: "Product Create",
  description: "Generated by create next app",
};

const ProductCreate = async ({ params: { id } }) => {

  const supabase = createClient();

  const response = await supabase
    .from('Brands')
    .select();

  return (
    <Container>
      <Card className='p-4 mb-4'>
        <Row>
          <Col><h3>Product Create</h3></Col>
          <Col className='text-end'><Link href={`/products`} >Products</Link></Col>
        </Row>
        <ProductForm product={{ price: 0, sale_price: 0 }} brands={response?.data} />
      </Card>
    </Container>
  )
}

export default ProductCreate