import { createClient } from '@/utils/supabase/server';
import React from 'react'
import ProductForm from '../../ProductForm';
import { Card, Col, Container, Row } from 'react-bootstrap';
import Link from 'next/link';


export const metadata = {
  title: "Product Edit",
  description: "Generated by create next app",
};

const ProductEdit = async ({ params: { id } }) => {
  const supabase = createClient();

  const response = await supabase
    .from('Brands')
    .select();

  const { data, error } = await supabase
    .from('Products')
    .select(`
  *,
  Brands (
    name 
  )
`).eq("id", id).single();
  return (
    <Container>
      <Card className='p-4 mb-4'>
        <Row>
          <Col><h3>Product Update</h3></Col>
          <Col className='text-end'><Link href={`/products`} >Products</Link></Col>
        </Row>
        <ProductForm product={data} brands={response?.data} />
      </Card>
    </Container>
  )
}

export default ProductEdit