import "bootstrap/dist/css/bootstrap.min.css";
import "@icon/themify-icons/themify-icons.css";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import AOSEffect from "./components/AOSEffect";
import { createClient } from "@/utils/supabase/server";

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body>
        <AOSEffect>
          <Header isLoggedIn={Boolean(user)} />
          {children}
          <Footer />
        </AOSEffect>
      </body>
    </html>
  );
}
