import "bootstrap/dist/css/bootstrap.min.css";
import "@icon/themify-icons/themify-icons.css";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import AOSEffect from "./components/AOSEffect";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <AOSEffect>
          <Header></Header>
          {children}
          <Footer></Footer>
        </AOSEffect>
      </body>
    </html>
  );
}
