import { createClient } from "@/utils/supabase/server";
import Banner from "@/components/Home/Banner";
import LatestModels from "@/components/Home/LatestModels";


export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default async function Home() {

  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();

  return (
    <main>
      <Banner />
      <LatestModels />
    </main>
  );
}
